package squill;
/**
 * All writable data classes generated by mgen should extend this interface
 * @author Jevgeni Martjushev
 *
 */
public interface WritableDataObject extends ReadableDataObject {
	void insert(Squill squill);
	void update(Squill squill);
	void delete(Squill squill);
}
